DROP TABLE user_startup;
DROP TABLE user_role;
DROP TABLE role_permission;
DROP TABLE startup_evaluation;
DROP TABLE user;
DROP TABLE startup;
DROP TABLE role;
DROP TABLE permission;
DROP TABLE category;